# Use root/example as user/password credentials
version: '3.5'

# Network
networks:
  backend:
      driver: bridge

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123123
    ports:
      - 27017:27017
    networks:
      - backend

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123123
    networks:
      - backend 

  mysql:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123123
    ports:
      - 3306:3306
    networks:
      - backend  

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
    depends_on: 
      - mysql
    restart: always
    ports:
      - 8082:80
    volumes:
      - /sessions
    networks:
      - backend